# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Русская версия сайта
ru:
  languageCode: 'ru-ru'
  contentDir: 'content/ru/'   # Контент на русском языке
  title: 'Ж. Виеру'
  date_format: '2025-05-30'
  address:
    street: 'ул. Орджоникидзе, 3'
    city: 'г. Москва'
    region: 'Российская Федерация'
    postcode: '115419'
    country: 'Российская Федерация'
    country_code: 'RU'
  address_format: 'zh'  # Если нужно, иначе можно убрать
  menu:
    main:
      - name: 'Блог'
        url: 'post/'
        weight: 20
      - name: 'Проекты'
        url: 'project/'
        weight: 30
      - name: 'Публикации'
        url: 'publication/'
        weight: 40
      - name: 'Обсуждения'
        url: '/#talks'
        weight: 12
      - name: 'Новости'
        url: '/#news'
        weight: 13
      - name: 'Опыт'
        url: 'experience/'
        weight: 20
      - name: 'Обучение'
        url: 'teaching/'
        weight: 40

# Английская версия сайта
en:
  languageCode: 'en-us'
  contentDir: 'content/en/'   # Content in English
  title: 'G. Vieru'
  date_format: '2025-05-30'
  menu:
    main:
      - name: 'Blog'
        url: 'post/'
        weight: 20
      - name: 'Projects'
        url: 'project/'
        weight: 30
      - name: 'Publications'
        url: 'publication/'
        weight: 40
      - name: 'Talks'
        url: '/#talks'
        weight: 12
      - name: 'News'
        url: '/#news'
        weight: 13
      - name: 'Experience'
        url: 'experience/'
        weight: 20
      - name: 'Teaching'
        url: 'teaching/'
        weight: 40
